"""add portfolio_delivery_settings

Revision ID: 2f11df3f9399
Revises: 9da148a4b67f
Create Date: 2026-05-19 10:08:40.276943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f11df3f9399'
down_revision: Union[str, Sequence[str], None] = '9da148a4b67f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_delivery_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('webhook_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('webhook_format', sa.String(length=16), server_default='json', nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_delivery_settings')
    # ### end Alembic commands ###
