"""add_delivery_timezone_to_portfolio_delivery_settings

Revision ID: 5a1f812d854e
Revises: e7e862e8d95e
Create Date: 2026-05-21 09:35:24.364245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a1f812d854e'
down_revision: Union[str, Sequence[str], None] = 'e7e862e8d95e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_delivery_settings', sa.Column('delivery_timezone', sa.String(length=64), server_default='UTC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_delivery_settings', 'delivery_timezone')
    # ### end Alembic commands ###
