"""add_run_outcomes

Revision ID: 6bf8567fca82
Revises: a1b2c3d4e5f6
Create Date: 2026-05-06 18:07:57.621893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf8567fca82'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_outcomes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('analysis_date', sa.String(), nullable=False),
    sa.Column('price_at_analysis', sa.Float(), nullable=True),
    sa.Column('price_7d', sa.Float(), nullable=True),
    sa.Column('price_14d', sa.Float(), nullable=True),
    sa.Column('price_30d', sa.Float(), nullable=True),
    sa.Column('price_90d', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_outcomes')
    # ### end Alembic commands ###
