"""add portfolio_thesis_crossrefs table

Revision ID: 9da148a4b67f
Revises: a1b01a59341f
Create Date: 2026-05-18 22:12:09.287700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9da148a4b67f'
down_revision: Union[str, Sequence[str], None] = 'a1b01a59341f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_thesis_crossrefs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('llm_provider', sa.String(), nullable=False),
    sa.Column('llm_model', sa.String(), nullable=False),
    sa.Column('thesis_text', sa.Text(), nullable=False),
    sa.Column('thesis_text_preview', sa.String(length=200), nullable=False),
    sa.Column('alignment_score', sa.Integer(), nullable=True),
    sa.Column('thesis_summary', sa.Text(), nullable=True),
    sa.Column('aligned_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('misaligned_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_exposure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excess_exposure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('holdings_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_thesis_crossrefs_portfolio_id'), 'portfolio_thesis_crossrefs', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_thesis_crossrefs_portfolio_id'), table_name='portfolio_thesis_crossrefs')
    op.drop_table('portfolio_thesis_crossrefs')
    # ### end Alembic commands ###
