"""add investor_profiles table

Revision ID: a1b01a59341f
Revises: e1f2a3b4c5d6
Create Date: 2026-05-18 07:53:34.946207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1b01a59341f'
down_revision: Union[str, Sequence[str], None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investor_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('income_range', sa.String(length=32), nullable=True),
    sa.Column('liquidity_reserve', sa.Text(), nullable=True),
    sa.Column('dependents', sa.Integer(), nullable=True),
    sa.Column('time_horizon', sa.String(length=16), nullable=True),
    sa.Column('risk_willingness', sa.Integer(), nullable=True),
    sa.Column('risk_ability', sa.String(length=16), nullable=True),
    sa.Column('investment_style', sa.String(length=16), nullable=True),
    sa.Column('sizing_approach', sa.String(length=24), nullable=True),
    sa.Column('preferred_sectors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('blind_spots', sa.Text(), nullable=True),
    sa.Column('emotional_tendencies', sa.Text(), nullable=True),
    sa.Column('personal_rules', sa.Text(), nullable=True),
    sa.Column('anti_portfolio', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_portfolio_size', sa.String(length=16), nullable=True),
    sa.Column('income_goal', sa.String(length=16), nullable=True),
    sa.Column('milestones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_index(op.f('ix_portfolio_insights_generated_at'), table_name='portfolio_insights')
    op.drop_index(op.f('ix_portfolio_insights_portfolio_id'), table_name='portfolio_insights')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_portfolio_insights_portfolio_id'), 'portfolio_insights', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_insights_generated_at'), 'portfolio_insights', ['generated_at'], unique=False)
    op.drop_table('investor_profiles')
    # ### end Alembic commands ###
