"""add telegram_chat_id to portfolio_delivery_settings

Revision ID: e7e862e8d95e
Revises: 2f11df3f9399
Create Date: 2026-05-19 12:08:48.766273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e862e8d95e'
down_revision: Union[str, Sequence[str], None] = '2f11df3f9399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_delivery_settings', sa.Column('telegram_chat_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_delivery_settings', 'telegram_chat_id')
    # ### end Alembic commands ###
